user/basic_app/urls.py
from django.urls import path, re_path, include
from basic_app import views


app_name = 'basic_app'

urlpatterns = [
    re_path('^register/$', views.register, name = 'register'),
    re_path(r'^user_login/', views.user_login, name = 'user_login')
]

user/user/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from basic_app import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name = 'index'),
    re_path(r'^basic_app/',include('basic_app.urls')),
    re_path(r'^logout/$', views.user_logout, name = "logout")
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank=True)

    def __str__(self):
        return self.user.username

user/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

user/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout


def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)


    user_form = UserForm()
    profile_form = UserProfileInfoForm()
    context = {'user_form':user_form,
               'profile_form':profile_form,
               'registered':registered}

    return render(request, 'basic_app/registration.html', context)

def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')

        else:
            print("Someone tried to login and failed")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse('Invalid login details supplied')

    else:
        return render(request,'basic_app/login.html')

user/basic_app/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{%url 'index'%}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{%url 'admin:index'%}">Admin</a>
        <a class="nav-item nav-link" href="{%url 'basic_app:register'%}">Register</a>

      {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{%url 'logout'%}">Logout</a>

          {% else %}
            <a class="nav-item nav-link" href="{%url 'basic_app:user_login'%}">Login</a>
      {% endif %}

      </div>
    </div>
  </nav>

  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>

</body>

</html>

user/basic_app/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}

{% block body_block %}

  <div class="jumbotron">
    <h1>INDEX</h1>
  </div>

{% endblock %}

user/basic_app/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}

{%block body_block%}
  <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{url 'basic_app:user_login'}" method="post">
      {% csrf_token %}

      <label for="username"></label>
      <input type="text" name="username" placeholder="Enter username">

      <label for="password">Password</label>
      <input type="text" name="password">

      <input type="submit" name="" value="login">

    </form>
  </div>
{%endblock%}

user/basic_app/templates/basic_app/media_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {{ media 'profile_pics/dog.jpg' }}
  </body>
  {{  }}
</html>

user/basic_app/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
  <h1>thank u for registering</h1>

  {% else %}
  <h1>register here</h1>
  <h3>fill out the form</h3>

  <form enctype="multipart/form-data" , method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Register">

  </form>

  {% endif %}
</div>

{% endblock %}